on: [push]

name: Build Docker images

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: '${{ secrets.DOCKER_PASSWORD }}'
  DOCKER_ORGANIZATION: philipssoftware
  GITHUB_ORGANIZATION: philips-software
  COSIGN_PRIVATE_KEY: '${{ secrets.COSIGN_PRIVATE_KEY }}'
  COSIGN_PASSWORD: '${{ secrets.COSIGN_PASSWORD }}'
  COSIGN_PUBLIC_KEY: '${{ secrets.COSIGN_PUBLIC_KEY }}'

jobs:
  build_containers:
    name: Build containers 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: python-buster
            dockerfile: 3/vanilla 
            tags: latest buster 3.9
          - name: python-tox
            dockerfile: 3/tox 
            tags: tox tox-3 tox-3.20 tox-3.20.1
          - name: python-with-openjdk
            dockerfile: 3/openjdk 
            tags: java java-3 java-3.9 
    steps:
      - uses: actions/checkout@v2.4.0
      - name: ${{ matrix.name }} 
        uses: philips-software/docker-ci-scripts@v4.1.2
        with:
          dockerfile: ${{ matrix.dockerfile }} 
          image-name: python
          tags: ${{ matrix.tags }}
          push-branches: main
          slsa-provenance: true
          sign: true
          sbom: true

