on: [push]

name: Build Docker images

jobs:
  build_python_buster:
    name: Build Python Buster <3
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: Build Docker Images with python
      run: |
        ./ci/docker_build_and_push.sh 3/vanilla-python python:buster
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: '${{ secrets.DOCKER_PASSWORD }}'
        DOCKER_ORGANIZATION: ${{ secrets.DOCKER_ORGANIZATION }}
        GITHUB_ORGANIZATION: ${{ secrets.GITHUB_ORGANIZATION }}
