on: [push]

name: Build Docker images

env:
  REGISTRY_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  REGISTRY_TOKEN: '${{ secrets.DOCKER_PASSWORD }}'
  DOCKER_ORGANIZATION: philipssoftware
  GITHUB_ORGANIZATION: philips-software
  KEYLESS: true

jobs:
  build_containers:
    name: Build containers 
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      packages: write
    strategy:
      matrix:
        include:
          - name: python-buster
            dockerfile: 3/vanilla 
            tags: latest buster 3.9
          - name: python-tox
            dockerfile: 3/tox 
            tags: tox tox-3 tox-3.20 tox-3.20.1
          - name: python-with-openjdk
            dockerfile: 3/openjdk 
            tags: java java-3 java-3.11 java-3.11.2
    steps:
      - uses: actions/checkout@v3
      - name: ${{ matrix.name }} 
        uses: philips-software/docker-ci-scripts@v5.0.0
        with:
          dockerfile: ${{ matrix.dockerfile }} 
          image-name: python
          tags: ${{ matrix.tags }}
          push-branches: main
          slsa-provenance: true
          sign: true
          sbom: true

