on: [push]

name: Build Docker images

jobs:
  build_python_buster:
    name: python-buster
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Images
      uses: philips-software/docker-ci-scripts@v3.1.0
      with:
        dockerfile: 3/vanilla 
        image-name: python
        tags: latest buster 3.9
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: '${{ secrets.DOCKER_PASSWORD }}'
        DOCKER_ORGANIZATION: philipssoftware
        GITHUB_ORGANIZATION: philips-software

  build_python_tox:
    name: python-tox
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build Images
      uses: philips-software/docker-ci-scripts@v3.1.0
      with:
        dockerfile: 3/tox 
        image-name: python
        tags: tox tox-3 tox-3.20 tox-3.20.1
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: '${{ secrets.DOCKER_PASSWORD }}'
        DOCKER_ORGANIZATION: philipssoftware
        GITHUB_ORGANIZATION: philips-software

  build_python_with_openjdk:
    name: python-openjdk
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build Images
      uses: philips-software/docker-ci-scripts@v3.1.0
      with:
        dockerfile: 3/openjdk 
        image-name: python
        tags: java java-3 java-3.9 
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: '${{ secrets.DOCKER_PASSWORD }}'
        DOCKER_ORGANIZATION: philipssoftware
        GITHUB_ORGANIZATION: philips-software
